apiVersion: v1
kind: Service
metadata:
  name: identity
  namespace: soa-app
  labels:
    app: identity
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 5226
      targetPort: 5226
  selector:
    io.kompose.service: identity
