apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgdata-stakeholders
  namespace: soa-app
  labels:
    app: postgres-stakeholders
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
