apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stakeholders-images
  namespace: soa-app
  labels:
    app: stakeholders
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
