apiVersion: v1
kind: Service
metadata:
  name: tour
  namespace: soa-app
  labels:
    app: tour
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 5229
      targetPort: 5229
  selector:
    io.kompose.service: tour
