global:
  scrape_interval: 15s  # koliko ƒçesto prikuplja metrike

scrape_configs:
  - job_name: 'dotnet_services'
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'tour:5229'

  - job_name: 'host_metrics'
    static_configs:
      - targets: ['node-exporter:9100']
