global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'dotnet_services'
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'tour:5229'

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'grafana'
    static_configs:
     - targets: ['grafana:3000']


  - job_name: 'docker_stats'
    static_configs:
      - targets: ['docker-stats-exporter:9487']
