apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity
  namespace: soa-app
  labels:
    app: identity
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: identity
  template:
    metadata:
      labels:
        io.kompose.service: identity
        app: identity
    spec:
      containers:
        - name: identity
          image: {{ACR_NAME}}.azurecr.io/identity:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ASPNETCORE_ENVIRONMENT
            - name: ASPNETCORE_URLS
              value: http://+:5226
            - name: AUDIENCE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: AUDIENCE
            - name: ISSUER
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ISSUER
            - name: NATS_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: NATS_URL
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SECRET_KEY
            - name: DB_CONNECTION_STRING_IDENTITY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_CONNECTION_STRING_IDENTITY
          ports:
            - name: http
              containerPort: 5226
              protocol: TCP
          resources:
            requests:
              memory: "128Mi"
              cpu: "200m"
            limits:
              memory: "256Mi"
              cpu: "500m"
      restartPolicy: Always
