apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-tours
  namespace: soa-app
  labels:
    app: postgres-tours
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres-tours
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: postgres-tours
        app: postgres-tours
    spec:
      containers:
        - name: postgres-tours
          image: postgres:16-alpine
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: POSTGRES_DB_TOUR
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: POSTGRES_USER_TOUR
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_PASSWORD_TOUR
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pgdata-tours
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U postgres -d tour
            failureThreshold: 5
            periodSeconds: 10
            initialDelaySeconds: 30
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U postgres -d tour
            failureThreshold: 3
            periodSeconds: 5
            initialDelaySeconds: 10
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
      restartPolicy: Always
      volumes:
        - name: pgdata-tours
          persistentVolumeClaim:
            claimName: pgdata-tours
