apiVersion: v1
kind: Service
metadata:
  name: postgres-tours
  namespace: soa-app
  labels:
    app: postgres-tours
spec:
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  selector:
    io.kompose.service: postgres-tours
  type: ClusterIP
